name = "cli-tools"
main = "src/index.ts"
compatibility_date = "2026-07-17"
workers_dev = true

routes = [
  { pattern = "cli-tools.cpzhmlb.lat", custom_domain = true }
]

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "cli-tools"

[vars]
PUBLIC_BASE_URL = "https://cli-tools.cpzhmlb.lat"
